gemu:
  build: ..
  hostname: gemu-hhvm
#  links:
#    - redis:redis.local
  volumes:
    - /dev/log:/dev/log
    - ../:/var/www/html/gemu
    - ./etc/hhvm/php.ini:/etc/hhvm/php.ini:ro
  working_dir: /var/www/html/gemu
#  restart: always


nginx:
  image: nginx
  hostname: gemu-nginx
  links:
    - gemu
  ports:
    - "8080:80"
#  restart: always
  volumes:
    - ./etc/nginx/sites-available/gemu.conf:/etc/nginx/conf.d/default.conf:ro
    - ../web/assets/:/var/www/html/gemu/web/assets
    - /dev/log:/dev/log

#redis:
#  image: redis
#  restart: always
